server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: dashboard-service
          uri: http://localhost:8001
        - id: data-service
          uri: http://localhost:8002
        - id: common-service
          uri: http://localhost:8003