server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka/

spring:
  application:
    name: gateway-service
  profiles:
    active: sun2824
  cloud:
    gateway:
      routes:
        - id: dashboard-service
          uri: http://localhost:8001
        - id: data-service
          uri: http://localhost:8002
        - id: common-service
          uri: http://localhost:8003
  datasource:
    hikari:
      common:
        jdbc-url: jdbc:mariadb://localhost:3306/common?useUnicode=yes&characterEncoding=UTF-8
        driver-class-name: org.mariadb.jdbc.Driver
        username: sun2824
        password: 1q2w3e4r!!
        pool-name: hikari-common
        minimum-idle: 1
        maximum-pool-size: 2
        connection-test-query: SELECT 1